### PR TITLE
Configurable Tmp Dir Location

### LINKED ISSUE #2544: [Testing] `tmp` location in `vendor` causes annoyance for local development
## Bug Report

**Current Behavior**
I've run into an issue that will be annoying for local development but should not affect automated testing. Currently, the installation setup script stores data from the simulated environment in the `tmp` directory, and more importantly, the cached `config.php`, which, as a result of the package's extraction, will now be located in `vendor`, not with the test source code. So, it will be wiped on every composer update, and as a result, developers will need to re-run `composer test:setup` whenever they make any composer changes. They will also need to run `composer test:setup` individually for every flarum extension. 

This is problematic because if the database used for tests exists when `composer test:setup` is run, the setup script will crash, and testing config (which is necessary to run tests) won't be cached. Right now, developers need to completely delete and recreate the test DB every time they want to configure tests for a new database, which is very annoying.

**Possible Solution**
1. Leave this to extension developers. This may include:
    1. Recommend that developers destroy and re-create the test database between running local tests for various extensions
    2. Recommend that different databases be used for testing different extensions
1. Store the `tmp` directory for each extension in that extension's test code. We would need to somehow provide the path to this tmp directory to both `SetupScript.php` (easy to do through each package's `setup.php`), and to `TestCase` (not as trivial, perhaps possible through `$argv`, `$argc`)
1. Recommend that extension devs install the testing package globally; this makes it much simpler to reuse the same `tmp` directory for all tests, but makes it more challenging to use separate dbs for separate packages if that's something the developer wants to do. Also, global requirements can get messy very fast, so I don't like this one at all
1. Add support for a composer command as an alternative to `test:setup` that would confirm that DB credentials work and write a config.php, but not install anything. This would make rerunning `test:setup` much simpler when a DB already exists, but makes inconsistent state more likely, would prove problematic as core adds migrations, and adds a LOT of unnecessary boilerplate code as we'll need to redo portions of `Installation`, which also means that if we change that in core, we'll also need to change it in testing.
1. If an env var (`FLARUM_TEST_DATA_DIR`) exists, use that for the path to `tmp`. This allows developers to use one shared `tmp` directory for all packages, which won't be overriden every time composer is updated. However, it doesn't impose anything, as the default `tmp` would still be used if that env var isn't provided.

My preferred approach is (#)5.
**Additional Context**

### PR DESCRIPTION
**Pull request by askvortsov1**
Fixes https://github.com/flarum/core/issues/2544, I went with the agreed-upon approach.

This also allows us to not include a copy of the tmp dir in the source code. Alternatively we could have kept it and copied that, but then we'd need a recursive copy function which is a pain.

### CODE REVIEW

File: src/integration/UsesTmpDir.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+trait UsesTmpDir
+{
+    protected $DEFAULT_TMP_DIR = __DIR__.'/tmp';
+
+    public function tmpDir() {
+        return realpath(getenv('FLARUM_TEST_TMP_DIR_LOCAL') ?: getenv('FLARUM_TEST_TMP_DIR') ?: static::$DEFAULT_TMP_DIR);
+    }
+
+    public function setupTmpDir() {
```
Comment (SychO9) [inline src/integration/UsesTmpDir.php:11]: Wasn't the tmp dir setup by the setup script ?

File: src/integration/UsesTmpDir.php [hunk 2]
```diff
@@ -0,0 +1,46 @@
+<?php
+
+namespace Flarum\Testing\integration;
+
+trait UsesTmpDir
+{
+    protected $DEFAULT_TMP_DIR = __DIR__.'/tmp';
+
+    public function tmpDir() {
+        return realpath(getenv('FLARUM_TEST_TMP_DIR_LOCAL') ?: getenv('FLARUM_TEST_TMP_DIR') ?: static::$DEFAULT_TMP_DIR);
```
Comment (SychO9) [inline src/integration/UsesTmpDir.php]: Aren't we supposed to use the current working directory path with one of the variables ?

Also, why two variables instead of one ?

File: src/integration/UsesTmpDir.php (hunk 1 above)
Comment (askvortsov1) [reply src/integration/UsesTmpDir.php:11]: It was, but that uses this function.

File: src/integration/UsesTmpDir.php (hunk 2 above)
Comment (askvortsov1) [reply src/integration/UsesTmpDir.php]: > Aren't we supposed to use the current working directory path with one of the variables ?

Doesn't `static::$DEFAULT_TMP_DIR` do that already?

> Also, why two variables instead of one ?

This way, a local config var can be set independently of a global config var.

Comment (SychO9) [reply src/integration/UsesTmpDir.php]: > This way, a local config var can be set independently of a global config var.
I see

> Doesn't `static::$DEFAULT_TMP_DIR` do that already?

Not sure if we're talking about the same thing then, that property's value will always be the path `vendor/flarum/testing/src/integration/tmp`. But it doesn't matter either way, I was actually wrong, we don't need to use getcwd with the env variables, because using a relative path value will work just fine.

That said, the property isn't static but you're calling it statically, but since it's only used in one spot, I'd rather it be hardcoded tbh, just to avoid the uppercase variable to look like a constant but isn't actually one issue :p

File: src/integration/UsesTmpDir.php (hunk 1 above)
Comment (SychO9) [reply src/integration/UsesTmpDir.php:11]: I'm probably missing something. It didn't use it before and it still created the tmp dir, so why does it need to use this method now ?

Comment (askvortsov1) [reply src/integration/UsesTmpDir.php:11]: Previously, the source code included a skeleton structue via `.gitkeep` files (removed in https://github.com/flarum/testing/pull/2/commits/d1ee17c0666cf0c39d03afe8a46cadbd891c3404 as part of this PR). Instead of that, this approach will automatically create the tmp dir structure in whatever folder is selected.

File: src/integration/UsesTmpDir.php (hunk 2 above)
Comment (askvortsov1) [reply src/integration/UsesTmpDir.php]: > that property's value will always be the path vendor/flarum/testing/src/integration/tmp

Well, yes. I thought the plan from https://github.com/flarum/core/issues/2544 was to use the vendor location for the default tmp dir, to avoid making assumptions about how an extension might decide to structure its code.

> That said, the property isn't static but you're calling it statically, but since it's only used in one spot

Done, since it's only used in one place in one class, I think hardcoding is fine here.

Comment (SychO9) [reply src/integration/UsesTmpDir.php]: yup that was always the plan, I just got confused and forgot that with the env variables we can also just use relative paths, since such a path will be relative to the current working directory.

File: src/integration/UsesTmpDir.php (hunk 1 above)
Comment (SychO9) [reply src/integration/UsesTmpDir.php:11]: Makes sense, thank you for the clarification, I totally missed that.

**Review by SychO9 — COMMENTED** [review]
So, I tried running the setup with an extension, and I found an issue. The setup fails to create the tmp directory, because `realpath` returns false, when the file or directory path given does not exist.

There doesn't seem to be any other vanilla functions which return the absolute path without caring for the existence of the file/dir. We could implement our own, but I think we might be able to just drop using realpath anyway? thoughts?

**Comment by askvortsov1** [comment]
Fixed!

**Review by SychO9 — APPROVED** [review]
Code looks good, tested all three path variations and worked just fine. Only one nitpick to lowercase the variables in `setupTmpDir` method, but not a blocker.

**Review by luceos — APPROVED** [review]
