### PR TITLE
Drop all DB tables before installation during setup.

### LINKED ISSUE #2718: [Testing] No way to run an extension's migration during setup
## Bug Report

When using `flarum/testing` in a community extension, there's no way of running the migrations during setup, so it's not possible to run integration tests that use new database tables/columns.

**Environment**
- Flarum version: beta 16

**Possible Solution**

We need a way to pass an array of community extensions to run migrations for to `Flarum\Testing\integration\Setup\SetupScript` in our `setup.php` file. One might not be enough, if our extension depends on other community extensions we will also want to run those other migrations.

Ideally we should also be able to pass other `Step` classes to add to the `$pipeline` to further customize the setup without having to copy the full setup class.

This is the very crude implementation I made for my extension. But ideally I think we should merge this with the step that enables the core extensions.

```php
<?php

namespace Kilowhat\Formulaire\Tests\integration;

use Flarum\Database\DatabaseMigrationRepository;
use Flarum\Database\Migrator;
use Flarum\Extension\Extension;
use Flarum\Install\DatabaseConfig;
use Flarum\Install\Step;
use Flarum\Install\Steps\ConnectToDatabase;
use Illuminate\Filesystem\Filesystem;

class EnableFormulaireInstallStep implements Step
{
    protected $dbConfig;
    protected $db;

    public function __construct(DatabaseConfig $dbConfig)
    {
        $this->dbConfig = $dbConfig;
    }

    public function getMessage()
    {
        return 'Enabling Formulaire extension';
    }

    public function run()
    {
        $connect = new ConnectToDatabase($this->dbConfig, function ($db) {
            $this->db = $db;
        });

        $connect->run();

        $migrator = new Migrator(
            new DatabaseMigrationRepository($this->db, 'migrations'),
            $this->db,
            new Filesystem
        );

        $extension = new Extension(__DIR__ . '/../..', [
            'name' => 'kilowhat/flarum-ext-formulaire',
        ]);

        $extension->migrate($migrator);
    }
}
```

In `setup.php`, inside `SetupScript::run`:

```php
    $pipeline->pipe(function () use ($dbConfig) {
            return new EnableFormulaireInstallStep($dbConfig);
        });
```

**Additional Context**
This affects my Formulaire extension which was previously using a modified copy of core's integration tests. The code above is what I already used for Flarum beta 15.

### PR DESCRIPTION
**Pull request by askvortsov1**
This ensures a clean state for the extension currently being tested. The alternative requires the user to create and keep track of multiple test databases, or manually delete/re-recreate the database every time they switch between extensions being tested. Now, a simple `composer test:setup` will always reset the test environment to the original state.

Fixes https://github.com/flarum/core/issues/2718

### CODE REVIEW

File: src/integration/Setup/SetupScript.php [hunk 1]
```diff
@@ -122,4 +128,19 @@ public function run()
 
         echo "Installation complete\n";
     }
+
+    // Copied from https://stackoverflow.com/questions/3493253/how-to-drop-all-tables-in-database-without-dropping-the-database-itself/3493398
+    protected function dropDbTables()
+    {
+        $mysqli = new mysqli($this->host, $this->user, $this->pass, $this->name);
```
Comment (clarkwinkelmann) [inline src/integration/Setup/SetupScript.php]: If we're just running MySQL queries, can't we just use the Laravel Query builder with raw statements?

It seems a bit odd to create a `mysqli` object just for this. Also does this add a new system requirement?

Comment (clarkwinkelmann) [reply src/integration/Setup/SetupScript.php]: Can't we just copy what Laravel has in its `migrate:fresh` command?

**Review by SychO9 — APPROVED** [review]
Code looks good, tested locally.

**Review by tankerkiller125 — APPROVED** [review]
